# STAGE 1 build the app
FROM node:10 AS build-stage

# Build the app
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/

# Check certificates
RUN sh -c '[ -f "/app/ssl_cert.pem" ] || { echo "!!!!!! Please put combined certificate as ssl_cert.pem at the same folder as Dockerfile !!!!!!"; exit 1; }'
RUN sh -c '[ -f "/app/ssl_key.pem" ] || { echo "!!!!!! Please put combined certificate as ssl_key.pem at the same folder as Dockerfile !!!!!!"; exit 1; }'

RUN npm run build

# STAGE 2 run nginx
FROM nginx:latest

COPY --from=build-stage --chown=root:root /app/ssl_cert.pem /ssl_certificate.bundle.crt
COPY --from=build-stage --chown=root:root /app/ssl_key.pem /ssl_certificate.key
RUN chmod 400 /ssl_certificate.bundle.crt
RUN chmod 400 /ssl_certificate.key

# Necessary files
COPY --from=build-stage --chown=root:root /app/build /app/build
COPY --from=build-stage --chown=root:root \
    /app/nginx_conf/covid_scholar_with_https.conf \
    /etc/nginx/conf.d/default.conf

EXPOSE 80
